#!/bin/bash
# Author: @FershoUno <https://github.com/FershoUno>
# Author: Jared Lopez <jared.lopez@openit.com.bo>

set -x			# debug
set -e                  # exit on error
set -o pipefail         # exit on pipeline error
set -u                  # treat unset variable as error

if [[ "$(whoami)" != "root" ]]
then
	echo "You need to run plurios-live as root"
	exit 1
fi

# === variables ===
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
CONF_VAR="config/variables.conf"
WORKSPACE="workspace"

# === load files ===
. $CONF_VAR || exit 1
. $CONF_PLURIOS || exit 1
. $LIB_PLURIOS || exit 1

# === main ===

function run(){

if [ -f $TEMPLATE_DIR/filesystem.squashfs ]; then
echo "File: filesystem.squashfs found.."
echo "Using Template"
  setup_workspace
  load_filesystem
  exec_chroot
  repack_filesystem
  build_iso
else
echo "File: filesystem.squashfs not found.."
echo "Creating template"
  get_content_iso
  create_template_squashfs
  load_filesystem
  exec_chroot
  repack_filesystem
  build_iso
fi
}

ISO_FILE="${1:-}"

echo "start: $(date)"
run
echo "end: $(date)"
