#!/bin/bash

echo "
#####################
# run 00-repository #
#####################
"

# update sources.list

cat <<EOF > /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse

# deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
# deb-src http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse
EOF


# update key brave browser
curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

apt-get update && apt-get upgrade -y
apt autoremove -y

