#!/bin/bash

echo "
#####################
# run 00-repository #
#####################
"

# update sources.list		(FOCAL commented)

#cat <<EOF > /etc/apt/sources.list
#deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
#deb http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse
#
## deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
## deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
## deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
## deb-src http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse
#EOF


# update sources.list		(NOBLE used)
#cat <<EOF > /etc/apt/sources.list
#deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu/ noble-proposed main restricted universe multiverse
#
##deb-src http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
##deb-src http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
##deb-src http://archive.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
##deb-src http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
##deb-src http://archive.ubuntu.com/ubuntu/ noble-proposed main restricted universe multiverse
#EOF



# update key brave browser
#curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

apt-get update && apt-get upgrade -y
apt autoremove -y


# Mozilla Firefox
install -d -m 0755 /etc/apt/keyrings
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null

echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null

echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | sudo tee /etc/apt/preferences.d/mozilla
