#!/bin/bash

echo "
#################
# run 01-kernel #
#################
"

#KERNEL_VERSION_UPDATED=$(dpkg --list | grep linux-image | grep ii | awk '{print $3}' | sort -r |head -n 1)
#KERNEL_NAME_UPDATED="linux-image-$(echo $KERNEL_VERSION_UPDATED | cut -d "." -f 1,2,3)-generic"
#LIST_KERNELS_REMOVE=$(dpkg --list | grep ii | grep -i linux-image | awk '{print $2}' | grep -v $KERNEL_NAME_UPDATED)
#
#for kernel in $LIST_KERNELS_REMOVE
#do
#  apt remove --purge --autoremove $kernel -y
#done
#
#apt autoremove -y
#
#KERNEL_DIR_UPDATED=$(echo $KERNEL_NAME_UPDATED | sed 's/linux-image-//')
#
#shopt -s extglob
#rm -rf /lib/modules/!($KERNEL_DIR_UPDATED) 2>/dev/null
#shopt -u extglob
#
## new initramfs
#update-initramfs -c -k $(ls /lib/modules/)
#
#update-grub

apt-get install -y linux-image-generic

update-grub
