#!/bin/bash

echo "
####################
# run 02-uninstall #
####################
"

apt remove --purge --autoremove -y \
	snapd \
	brasero \
	cheese \
	gedit \
	gnome-games \
	gnome-2048 \
	gnote \
	vim-tiny \
	hexchat \
	shotwell \
	gnome-mahjongg \
	pidgin \
	sound-juicer \
	ufw \
	synaptic \
	remmina \
	alacritty \
	gthumb

#apt remove -y \
#	hunspell-de-at-frami \
#	hunspell-de-ch-frami \
#	hunspell-de-de-frami \
#	hunspell-en-au \
#	hunspell-en-ca \
#	hunspell-en-gb \
#	hunspell-en-za \
#	hunspell-fr-classical \
#	hunspell-fr \
#	hunspell-it \
#	hunspell-pt-br \
#	hunspell-pt-pt \
#	hunspell-ru 

#apt remove --purge --autoremove	-y \
#	libreoffice-gtk 
#	libreoffice-gtk2

apt autoremove -y
