#!/bin/bash

echo "
########################
# run 05-configuration #
########################
"

#=========================
# set the system language
#=========================
sed -i 's/^# *\(es_BO.UTF-8 UTF-8\)/\1/' /etc/locale.gen
echo "LANG=es_BO.UTF-8" | tee /etc/default/locale
locale-gen
update-locale LANG=es_BO.UTF-8 LANGUAGE=es_BO.UTF-8 LC_ALL=es_BO.UTF-8
export LANG=es_BO.UTF-8
export LANGUAGE=es_BO.UTF-8
export LC_ALL=es_BO.UTF-8

# ===================================
# set the timezone (America/La_Paz)
# ===================================
echo "America/La_Paz" > /etc/timezone
ln -sf /usr/share/zoneinfo/America/La_Paz /etc/localtime
dpkg-reconfigure -f noninteractive tzdata

# ===================================================
# set the keyboard language (Spanish/Latin American)
# ===================================================
echo 'XKBLAYOUT="latam"' > /etc/default/keyboard
echo 'XKBMODEL="pc105"' >> /etc/default/keyboard
echo 'XKBVARIANT=""' >> /etc/default/keyboard
echo 'XKBOPTIONS=""' >> /etc/default/keyboard

update-initramfs -u

# ==================================================
# remove the snapd path from the environment file
# ==================================================
sed -i 's#:\/snap/bin##' /etc/environment

# ===============================================
# configures the values of the lsb_release file
# ===============================================
sed -i 's|^DISTRIB_DESCRIPTION=.*|DISTRIB_DESCRIPTION="PluriOS Metadistro Linux Boliviana"|' /etc/lsb-release

apt-get upgrade -y
