#!/bin/bash

echo "
#################
# run 99-finish #
#################
"
# remove 20apt-esm-hook.conf
rm -f /etc/apt/apt.conf.d/20apt-esm-hook.conf 2>/dev/null

# remove calamares
rm -f /usr/share/applications/calamares.desktop 2>/dev/null
rm -f /usr/share/applications/calamares-launch-oem.desktop 2>/dev/null
rm -f /usr/share/applications/ubuntu-unity-calamares.desktop 2>/dev/null

systemctl stop rustdesk 2>/dev/null
systemctl stop rustdesk-link 2>/dev/null
systemctl disable rustdesk 2>/dev/null
systemctl disable rustdesk-link 2>/dev/null

# generate snakeoil
make-ssl-cert generate-default-snakeoil --force-overwrite 2>/dev/null

# delete list packages
rm -rf /var/lib/apt/lists/* 2>/dev/null

apt-get upgrade -y

apt remove --purge --autoremove lp-solve -y 2>/dev/null

apt autoremove -y

update-initramfs -u

# Generate filesystem.manifest
dpkg-query -W --showformat='${Package} ${Version}\n' > /filesystem.manifest

