#!/bin/bash

echo "
#################
# run 99-casper #
#################
"

# rm -f /etc/casper.conf
cat <<EOF >/etc/casper.conf
# This file should go in /etc/casper.conf
# Supported variables are:
# USERNAME, USERFULLNAME, HOST, BUILD_SYSTEM, FLAVOUR

export USERNAME="plurios"
export USERFULLNAME="Live session PluriOS"
export HOST="plurios"
export BUILD_SYSTEM="Ubuntu"

# USERNAME and HOSTNAME as specified above won't be honoured and will be set to
# flavour string acquired at boot time, unless you set FLAVOUR to any
# non-empty string.

# export FLAVOUR="Ubuntu"
EOF

# update initramfs
update-initramfs -u 
