#!/bin/bash

echo "
####################
# run 00-uninstall #
####################
"
# ==========
# snapd
# ==========
apt remove --purge --autoremove -y snapd

# ==========
# office
# ==========
apt remove --purge --autoremove -y  gnome-text-editor fonts-noto libreoffice*

# ==========
# multimedia
# ==========
apt remove --purge --autoremove -y brasero cheese sound-juicer shotwell gthumb gnome-sound-recorder totem rhythmbox sonnet-plugins

# ===========
# games
# ===========
apt remove --purge --autoremove -y gnome-games gnome-2048 gnome-mahjongg

# ===========
# internet
# ===========
apt remove --purge --autoremove -y pidgin hexchat remmina w3m

# ===========
# graphics
# ===========
apt remove --purge --autoremove -y imagemagick imagemagick-6.q16 imagemagick-6-common eog

# ===========
# system
# ===========
apt remove --purge --autoremove -y gnote gedit gdebi lm-sensors fakeroot untex

# ===========
# tools
# ===========
apt remove --purge --autoremove -y alacritty ufw deja-dup apport \
	dracut-install gnome-characters gnome-logs html2text inetutils-telnet inxi \
	kerneloops neofetch vino

# ===========
# unnecessary languages
# ===========
apt remove --purge --autoremove -y \
        language-pack-de language-pack-de-base \
        language-pack-fr language-pack-fr-base \
        language-pack-ru language-pack-ru-base \
        language-pack-pt language-pack-pt-base

apt remove --purge --autoremove -y aspell-en wamerican
