# PluriOS configurator
# options: random name
NAME_ISO="plurios"

# options: "oit"
VARIANT_ISO="oit"

# options: "1.0" "1.0.2" or similar
VERSION_ISO="0.1"

# use option: "amd64" (i386 architecture is not supported)
ARCH_ISO="amd64"

# options: gzip, lzma, lzo, lz4, xz or zstd
COMPRESSION="zstd"

URL_SUPPORT="https://plurios.openit.dev"