# list of variables
LIB_PLURIOS="lib/plurioslib"
CONF_PLURIOS="config/plurios.conf"
CONF_CALAMARES="config/core/calamares.conf"
CONF_PREPARE_ISO="config/prepare-iso-live/prepare"
CONF_DOTFILES="config/dotfiles"
DIR_CONF_PLURIOS="config/plurios"
DIR_CONF_IMAGE="config/image"
DIR_CONF_CALAMARES="config/custom/calamares"
#BOOT_ISOLINUX_PLURIOS="config/core/live.cfg"
#BOOT_GRUB_PLURIOS="config/core/grub.cfg"
