# Configuration calamares
PLURIOS_TITLE_INSTALLER="PluriOS OIT"
PLURIOS_HELP_INSTALLER="PluriOS"
PLURIOS_VERSION_INSTALLER="${VERSION_ISO}"
PLURIOS_TITLE_CENTER_INSTALLER="PluriOS Metadistro Linux Boliviana"
PLURIOS_SHORT_VERSION_NAME_INSTALLER="PluriOS $PLURIOS_VERSION_INSTALLER"
PLURIOS_URL_ALL_INSTALLER="https://plurios.openit.dev"
