#!/bin/bash

echo "
#####################
# run 03-repository #
#####################
"
apt-get update && apt-get upgrade -y
#apt autoremove -y

# ========================
# Add PluriOS Repository
# ========================
wget -q https://nlbol.github.io/deb/plurios.gpg -O- | gpg --dearmor > /etc/apt/trusted.gpg.d/plurios.gpg
echo "deb https://nlbol.github.io/deb/plurios plurios main" | tee /etc/apt/sources.list.d/plurios.list

cat <<EOF> /etc/apt/preferences.d/plurios
Package: *
Pin: release l=PluriOS Repository
Pin-Priority: 1001
EOF

# ========================
# Add PluriOS Repository
# ========================

# Add Thunderbird
add-apt-repository ppa:mozillateam/ppa -y
apt-get update

cat <<EOF > /etc/apt/preferences.d/mozillateamppa
Package: thunderbird*
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001

Package: thunderbird*
Pin: release o=Ubuntu
Pin-Priority: -1
EOF

# Add Firefox
install -d -m 0755 /etc/apt/keyrings
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | tee /etc/apt/preferences.d/mozilla

# Add LibreOffice PPA
add-apt-repository -y ppa:libreoffice/ppa
apt-get update

